CREATE TABLE IF NOT EXISTS categories(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    description text
);
CREATE TABLE IF NOT EXISTS products(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    stock integer NOT NULL,
    categoryid integer REFERENCES categories(id)
);

INSERT INTO categories(name) values ('Latas');
INSERT INTO categories(name) values ('Carnes');
INSERT INTO categories(name) values ('Limpieza');
INSERT INTO categories(name) values ('Higiene');


INSERT INTO products(name,stock,categoryid) values ('Atun en lata',40,1);
INSERT INTO products(name,stock,categoryid) values ('Jabon',20,3);

INSERT INTO products(name,stock,categoryid) values ('Pollo',13,2);
INSERT INTO products(name,stock,categoryid) values ('Res',50,2);
INSERT INTO products(name,stock,categoryid) values ('Cerdo',95,2);